### ISSUE TITLE
vfsStream can't handle url encoded pathes

### ISSUE THREAD

**Issue by qrazi** [mikey179/vfsStream#104]
I wanted to write a testcase for loading XSD-files with DOMDocument (for more info, see https://github.com/goetas/xsd-reader/pull/10). To cover that specific case I need a directory path with a space character. Using vfsStream I got an error: `PHP Warning:  DOMDocument::load(): I/O warning : failed to load external entity "vfs://root/foo%20bar/schema.xsd"`

When I use a directorypath in vfsStream without space, the Xsd is loaded without problems. I have not figured out what causes this issue, so it could be this is actually not an issue for vfsStream.

For reproducing, see this gist: https://gist.github.com/qrazi/7789c1b1331336019bf7

**Comment by qrazi** [comment]
Tried to look into this. Found an [old bug-report for DOMDocument](https://bugs.php.net/bug.php?id=40656). Found in [IETF RFC 2396](http://tools.ietf.org/html/rfc2396#section-2.4.3) that in an URI, a space-character should be escaped by using percentage-encoding.

Tried to understand whats going on in [php-src\ext\dom\document.c](https://github.com/php/php-src/blob/master/ext/dom/document.c), especially functions [`dom_document_parser`](https://github.com/php/php-src/blob/master/ext/dom/document.c#L1355) and [`_dom_get_valid_file_path`](https://github.com/php/php-src/blob/master/ext/dom/document.c#L1301). 

There seems to be some stuff going on specifically for `file://`-based XML, so perhaps this is indeed not vfsStream's problem?

**Comment by mikey179** [comment]
Sorry for coming to this late, was away for some time.

Probably vfsStream must be able to handle encoded URLs properly, it might be that a stat call with an encoded URL returns that the URL doesn't exist, leading to this error message.
