### ISSUE TITLE
vfs directory structure is not reset after each test

### ISSUE THREAD

**Issue by ivanvermeyen** [mikey179/vfsStream#105]
Hi, I'm sorry if this is a noob question, but I was trying to get some tests to work with vfsStream and I bumped onto a problem. I'm not super experienced with this so I might be missing something?

Do I need to reset the structure in a tearDown/letgo method? I've been searching for this but couldn't find a clear answer so far...

I have put a demo of my issue here:
https://github.com/ivanvermeyen/testfilesystem
You can run `composer install` and `vendor/bin/phpspec run` on it.

I'm using phpSpec with this setup/let method:

    public function let()
    {
        $directoryStructure = [
            'test.txt' => 'test',
            'subDirectory' => [
                'subFile.txt' => 'subFile'
            ]
        ];

        vfsStream::setup('baseDirectory', null, $directoryStructure);
    }

If I create a directory or a file in a test, then it still exists in the next test, but only if I check if it exists:

    function it_creates_a_directory()
    {
        $this->exists(VfsStream::url('baseDirectory/newDirectory'))->shouldBe(false);
        $this->createDirectory(VfsStream::url('baseDirectory/newDirectory'));

        /**
         * If you uncomment the next line(s), the next test
         * will fail because newDirectory still exists
         */
        //$this->isDirectory(VfsStream::url('baseDirectory/newDirectory'))->shouldBe(true);
        //$this->exists(VfsStream::url('baseDirectory/newDirectory'))->shouldBe(true); // Same result...
    }

    function it_creates_unexisting_nested_directories()
    {
        $this->exists(VfsStream::url('baseDirectory/newDirectory'))->shouldBe(false); //=> This one fails...
        $this->createDirectory(VfsStream::url('baseDirectory/newDirectory/subDirectory/anotherDirectory'));
        $this->isDirectory(VfsStream::url('baseDirectory/newDirectory/subDirectory/anotherDirectory'))->shouldBe(true);
        $this->isDirectory(VfsStream::url('baseDirectory/newDirectory/subDirectory'))->shouldBe(true);

        /**
         * If you put this test before the other test,
         * then the next line(s) will also make the other test fail
         */
        $this->isDirectory(VfsStream::url('baseDirectory/newDirectory'))->shouldBe(true);
        $this->exists(VfsStream::url('baseDirectory/newDirectory'))->shouldBe(true); // Same result...
    }

The same is true for files:

    function it_creates_a_file()
    {
        $this->exists(VfsStream::url('baseDirectory/newFile.txt'))->shouldBe(false);
        $this->createFile(VfsStream::url('baseDirectory/newFile.txt'), 'some data');

        /**
         * If you uncomment the next line(s), the next test
         * will fail because newFile.txt still exists
         */
        //$this->readFile(VfsStream::url('baseDirectory/newFile.txt'))->shouldReturn('some data');
        //$this->isFile(VfsStream::url('baseDirectory/newFile.txt'))->shouldBe(true);
    }

    function it_should_not_find_a_file()
    {
        $this->exists(VfsStream::url('baseDirectory/newFile.txt'))->shouldBe(false);
    }

The class under test is very simple:
https://github.com/ivanvermeyen/testfilesystem/blob/master/src/Filesystem.php

**Comment by mikey179** [comment]
As I'm not familiar with phpSpec, is the `let()` method called before each single spec function is executed? If not, that's the problem then. Coming from PHPUnit: it's `setup()` is called before each test method, which resets vfsStream due to the new call to `vfsStream::setup()`.

**Comment by ivanvermeyen** [comment]
`let`is the equivalent of phpunit's `setup`  method. I did a quick check and it is indeed called before every test. I also tried calling `vfsStream::setup` and `vfsStream::create` in the tests, but that didn't help.

**Comment by mikey179** [comment]
Played around with your repo, it's a problem with the stat cache. Calling `clearstatcache()` in the `let()` method solves the problem. I think I'll add this call directly into `vfsStream::setup()` so a client doesn't have to do it manually. Funny that no one stumbled about the problem yet. :-)

**Comment by ivanvermeyen** [comment]
Cool :) Thanks for looking into it so fast!

**Comment by GerbenWijnja** [comment]
I would like to add something that cost me a while to realize. Using vfsStream in combination with PHPUnit "test dependencies" is kinda dangerous. You need to be careful not to reset or change the vfs between the depency and the dependent test, if the rootdir name is the same across tests. Example:
```php
<?php

use \org\bovigo\vfs\vfsStream;

class VfsTest extends \PHPUnit\Framework\TestCase
{
    public function testCreateFs()
    {
        // Create a test file
        $dir = vfsStream::setup('root', null, ['test.txt' => 'foo']);
        $this->assertTrue(true); // it's just an example, so make it pass...
        return $dir;
    }

    public function testCleanFs()
    {
        // This in-between test clears the filesystem
        vfsStream::setup('root', null, []);
        $this->assertTrue(true); // same...
    }

    /**
     * @depends testCreateFs
     */
    public function testFileExists($dir)
    {
        // This test depends on the return value of testCreateFs(),
        // but the filesystem will be empty!
        $this->assertFileExists($dir->url().'/test.txt');
    }
}
```
It it considered good practice to write your tests in a way that the order of the tests doesn't matter. Each test should be independent of the other tests. So the above example is bad practise.

I realize that propagating the $dir variable doesn't make sense here. I could just use vfsStream::url('root/test.txt') instead, but I felt this helps explaining the dependency.

What would be the best solution? I would say using @depends is ok. Just make sure that the vfs is setup at the start of each test. The order of test execution can change because of the dependencies, so always realize that each test must be properly setup. Maybe never pass the return value of vfsStream::setup() between tests...? Or only pass it if the root dir names are unique per test?
