### ISSUE TITLE
Please provides test

### ISSUE THREAD

**Issue by remicollet** [mikey179/vfsStream#108]
Since commit ba719af0e9d62ccc32214d2f3e04c820861714c8 test suite is no more provided, while useful in downstream distribution,

Please consider reverting this.

**Comment by mikey179** [comment]
Oh my... contradicting targets: small exports vs. providing everything in downstream distributions. I guess @sndsgd did it on purpose, maybe he wants to say something about it.

**Comment by sndsgd** [comment]
The changes in ba719af indeed were to create smaller distributions. I assumed that if people wanted to test this library, they'd be working with a clone of the repo, and therefore have everything.

**Comment by remicollet** [comment]
Thanks
