### ISSUE TITLE
Issue with combining wrappers

### ISSUE THREAD

**Issue by rickselby** [mikey179/vfsStream#121]
When trying to use compress.zlib in conjunction with vfs (i.e. `compress.zlib://vfs://root/test.nbt`) I get "cannot represent a stream of type user-space as a File Descriptor" when trying to use fopen.

Much googling hasn't turned up much on this issue; is this something that can be supported, or a limitation?

**Comment by mikey179** [comment]
Reopen, referenced the wrong issue id in the commit

**Comment by mikey179** [comment]
Which PHP version are you using? Trying this with PHP 5.6.4 I get the error message "failed to open stream: operation failed", not the one you have. Also, it seems the vfsStreamWrapper never gets called, so I'd suspect a limitation in PHP.

**Comment by rickselby** [comment]
It was 5.6.12 but admittedly on Windows. I'll test on Linux when I get a chance (though that'll be 5.5.9, Ubuntu 14.04) and get back to you.

**Comment by rickselby** [comment]
5.5.9 on linux gives both the "cannot represent a stream of type user-space as a File Descriptor" and "failed to open stream: operation failed" warnings.

**Comment by mikey179** [comment]
I took the time to investigate it further. I stumbled about the `stream_cast` method which until now only returns `false`, but could have a purpose now. I'm not sure if this feature should be added, as it can only work with a real file system interaction. But this should be discussed in PR #125, I'll close this issue for now.
