### ISSUE TITLE
Failing is_writable() on a directory with PHP 7.0

### ISSUE THREAD

**Issue by neufeind** [mikey179/vfsStream#123]
A testcase which works fine with for example php 5.6.x fails under php 7.0. is_writable() for a directory returns false for some reason. Doing a stat() on that directory returns the attached values. I expected that for example mode might be set wrong - but that imho looks okay as well.

array(26) {
[0]=>
int(0)
[1]=>
int(0)
[2]=>
int(16893)
[3]=>
int(0)
[4]=>
int(0)
[5]=>
int(0)
[6]=>
int(0)
[7]=>
int(0)
[8]=>
int(1449405664)
[9]=>
int(1449405664)
[10]=>
int(1449405664)
[11]=>
int(-1)
[12]=>
int(-1)
["dev"]=>
int(0)
["ino"]=>
int(0)
["mode"]=>
int(16893)
["nlink"]=>
int(0)
["uid"]=>
int(0)
["gid"]=>
int(0)
["rdev"]=>
int(0)
["size"]=>
int(0)
["atime"]=>
int(1449405664)
["mtime"]=>
int(1449405664)
["ctime"]=>
int(1449405664)
["blksize"]=>
int(-1)
["blocks"]=>
int(-1)
}

Just to mention it: I'm using vfsStream 1.6.1. I saw there were some fixes lately.

**Comment by neufeind** [comment]
Executing the same test as root works. I'm not using selinux or the like.

**Comment by mikey179** [comment]
As all the tests with `is_writable()` run fine with PHP 7 I'm not sure what to look into. Can you share the test case (or a small example) so that I can try to reproduce this?

**Comment by neufeind** [comment]
I don't have this easily reproducible. It fails for me when running the unittests from TYPO3 CMS 7 with PHP 7.0 on Fedora Linux. It works fine when running it with PHP 5.6. (And I've also heard that colleagues had no problem running them with PHP 7 on some other distro).
Do you have a PHP7-setup at hand? Would you be able to maybe grab a fresh git-checkout of TYPO3 and run the unit-tests (if so I could send you some details via email).

**Comment by neufeind** [comment]
I've tried to come up with easier examples. However there is_writable also seems to work fine for me. Weird.

**Comment by mikey179** [comment]
I have PHP 7 available on OS X (both Yosemite and El Capitan), so I could do a test run. I tried to clone https://github.com/TYPO3/TYPO3.CMS, but it doesn't contain any tests? I guess that's not where to look then...

**Comment by neufeind** [comment]
Should be correct. You'll need to do a "composer install" (not composer update) in that directory then, which will also pull in phpunit, vfsStream etc. Then you can execute "./bin/phpunit -c typo3/sysext/core/Build/UnitTests.xml" to run the unittests where several (vfsStream-related ones) fail for me with messages like:
49) TYPO3\CMS\Core\Tests\Unit\Cache\Backend\FileBackendTest::requireOnceThrowsExceptionForInvalidIdentifier with data set "pending multiple dots and slashes" ('myIdentifier.././../')
Failed asserting that exception of type "TYPO3\CMS\Core\Cache\Exception" matches expected exception "\InvalidArgumentException". Message was: "The directory "vfs://Foo/Cache/Data/UnitTestCache/" is not writable."

My Fedora Linux doesn't yet provide PHP 7.0, so I installed it from the remi-repository and load it via the scl-mechanism (software-collections) which basically sets environment-variables so PHP 7 is used instead of the one provided by the distro.

**Comment by mikey179** [comment]
Ah, I was missing the -c option.

On OS X Yosemite I don't get any failures, tests are running fine. I suspect the result on El Capitan will be similar, but can test this later only.

**Comment by neufeind** [comment]
Okay, let's forget about this ticket imho. Upgrading my main-php to a non-SCL-variant which now also is php 7.0.1 instead of 7.0.0 the unit-tests for vfsStream work as well. I expect those were problems of php or maybe of compilation-things because of SCL.
Thanks for your time to dig into this - and proving this was "my fault" :-) Of course it was somehow, since vfsStream ran fine on other systems.
