### ISSUE TITLE
Duplicate "valid" files/directories and incorrect file names - urlencoded/decoded problems?

### ISSUE THREAD

**Issue by cmthornton** [mikey179/vfsStream#128]
vfsStream::setup('root');
    $rootDir = vfsStream::url('root');
    $lostAndFound = "$rootDir/lost+found/";
    mkdir($lostAndFound);

    // 1. works, the `lost+found` directory name is valid
    $it = new RecursiveDirectoryIterator($lostAndFound);
    foreach ($it as $f) {
        printf("%s\n", $f);
    }
    // output:
    // vfs://root/lost+found/.
    // vfs://root/lost+found/..

    // 2. works, but should fail, the `lost found` directory name is *not* valid
    $it = new RecursiveDirectoryIterator("$rootDir/lost found/");
    foreach ($it as $f) {
        printf("%s\n", $f);
    }
    // output:
    // vfs://root/lost found/.
    // vfs://root/lost found/..

    // 3. works incorrectly, the parent directory will see a `lost found` directory, not `lost+found`
    $it = new RecursiveDirectoryIterator($rootDir);
    foreach ($it as $f) {
        printf("%s\n", $f);
    }
    // output:
    // vfs://root/.
    // vfs://root/..
    // vfs://root/lost found

I encountered this issue running version `1.6.1`.

I suspect `urldecode()` is responsible for the conversion from `+` to ` `. The conversion from `+` to ` ` (by `urldecode()` or some other function) seems to be fairly deep in the logic that builds `vfsStreamContainerIterator` objects, but I could not figure it out.

**Comment by cmthornton** [comment]
Thanks @mikey179!

**Comment by mikey179** [comment]
Thanks for the report! I released 1.6.2 with the fix today.
