### ISSUE TITLE
is_dir() returns False

### ISSUE THREAD

**Issue by Codealist** [mikey179/vfsStream#133]
Hi !
When i pass to testable method string directory returned by ` vfsStream::url('Serialized')`, and method uses condition `if(is_dir($path))`, it returns false, but not true.
`vfsStreamWrapper::getRoot()->hasChild('Serialized')` returns true.

Is it normal behavior ?
Thanks

**Comment by mikey179** [comment]
`vfsStream::url('Serialized')` is not the same as `vfsStreamWrapper::getRoot()->hasChild('Serialized')`. The first one yields _vfs://Serialized_, the latter has _vfs://root/Serialized_ (which you can check by`vfsStreamWrapper::getRoot()->getChild('Serialized')->url()` . Therefore it is correct that `is_dir('vfs://Serialized')` returns false, as this path likely doesn't exist.

**Comment by Codealist** [comment]
oh, i see. Now i pass `vfsStreamWrapper::getRoot()->getChild('Serialized')->url()` instead of `vfsStream::url('Serialized')` to is_dir() so it works correctly. Thanks a lot! I think this issue can be closed
