### ISSUE TITLE
Incompatibility between vfs and ImageMagick?

### ISSUE THREAD

**Issue by georaldc** [mikey179/vfsStream#139]
I'm currently using a library for manipulating images (Imagine) and was able to write tests easily while using Imagine's library with GD. I had to switch to their Imagick implementation though and noticed that all my tests that involve saving to my vfsstream directories were failing. It seems to fail when imagick's write functions are called (http://php.net/manual/en/imagick.writeimages.php in my case with Imagine). An exception with the following is what I get: "unable to open image `vfs:/my-custom-upload.jpg': No such file or directory". Writing image files will work though when using the actual file system.

Is there something preventing imagick from writing to my mocked file system? GD seems to work fine, as well as other file related functions that would have to do work with vfsstream.

**Comment by mikey179** [comment]
I never tested vfsStream with imagick, so I don't know if there's any incompatibility. However, the error message you mention looks like there is a slash missing in the vfsStream url, maybe that's the source of the problem?

**Comment by georaldc** [comment]
Sorry, mistyped that. Path was complete (vfs://custom-upload.jpg) so that probably wasn't it. The same code works just fine outside vfs so there's something else going on.

**Comment by georaldc** [comment]
Quick code sample that shows my problem. Using PHP 7.0.3 by the way
```
use org\bovigo\vfs\vfsStream;

vfsStream::setup('foo');
$image = new Imagick('image.jpg');
$image->writeImage('foo/image.jpg'); // works
$image->writeImage(vfsStream::url('foo/image.jpg')); // throws an exception: "unable to open image `vfs://foo/image.jpg': No such file or directory @ error/blob.c/OpenBlob/2641"
```

I can get the same error/exception thrown on an actual file system if the foo directory does not exist.

**Comment by mikey179** [comment]
From the error message and the ImageMagick code I looked at I suspect that this error message stems directly from ImageMagick. If the PHP extension is just a thin layer around ImageMagick and does not translate PHP streams into something that ImageMagick understands I fear that there's an incompatibility that vfsStream can nothing do about.

**Comment by georaldc** [comment]
That's what I was thinking as well. Guess I'll just modify my imagick related tests to not use vfsStream. Thanks.
