### ISSUE TITLE
Weird rename behavior

### ISSUE THREAD

**Issue by zzgab** [mikey179/vfsStream#140]
Hi.
Thank you for this great library.

I am facing a weird behavior when renaming folders (v1.6.4):

~~~~php
$vfs = vfsStream::setup('/');

vfsStream::create([
  'var' => [
    'file.txt' => "text"
  ]
]);

$vFile = $vfs->getChild('var')->getChild('file.txt');
echo $vFile->url();  
// prints: "vfs:///var/file.txt"

$vfs->getChild('var')
    ->rename('srv');

$vFile = $vfs->getChild('srv')->getChild('file.txt');
echo $vFile->url(); 
// still prints: "vfs:///var/file.txt"
// whereas I would expect "vfs:///srv/file.xt"

// But then: 
readfile( $vFile->url() ); // fails!
~~~~

Please note that, if I try to grab
~~~~php
$vFile = $vfs->getChild('var')->getChild('file.txt');
~~~~
after renaming "var" to "srv", the getChild fails. So, the `rename` operation did work, in the vfs memory.

Any idea if I'm doing something wrong?
Thanks.

**Comment by mikey179** [comment]
`rename()` on a child is an internal method only, which changes the name of the instance only, but not all the places it needs to be changed within a directory structure. You want to use [PHP's rename()](http://php.net/manual/en/function.rename.php) function, which should yield the correct result:

```
$vfs = vfsStream::setup('/')
vfsStream::create([
  'var' => [
    'file.txt' => "text"
  ]
]);
rename('vfs:///var', 'vfs:///srv');
```

As you can see in the [actual rename implementation](https://github.com/mikey179/vfsStream/blob/master/src/main/php/org/bovigo/vfs/vfsStreamWrapper.php#L787) renaming a file structure is much more complicated than simply renaming the value object itself.

As a general rule: modify vfs structures with filesystem functions only, not on the instance objects. Use vfs instance objects only to observe state, but not to change it.

**Comment by zzgab** [comment]
Thanks.

**Comment by georaldc** [comment]
Just treat vfs as you would your real world file system, using vfsSteam::url() to access the virtual directories themselves

```
$vFile = $vfs->getChild('var')->getChild('file.txt');
echo $vFile->url();  
// prints: "vfs:///var/file.txt"

rename(vfsStream::url('var'), vfsStream::url('srv'));

$vFile = $vfs->getChild('srv')->getChild('file.txt');
echo $vFile->url(); 
// prints: "vfs:///srv/file.txt"
```

**Comment by mikey179** [comment]
> So, creation of objects is OK, but modification is not?

Unfortunately it's not that simple. However, it might depend on what you want to achieve and what you want to use vfsStream for. The original use case was (and still is) to mock PHP's filesystem functions. In such cases it's sufficient to use the methods which obtain the current state of the different vfs objects for assertions, as modification is done through the filesystem functions and the vfs object modification methods are mainly for internal use within the library. PHP lacks ways of describing that properly with language constructs, and I haven't taken the efforts to document each single method with the annotations introduced by PHPDocumentor for such use cases.

**Comment by zzgab** [comment]
Thank you for the explanation. It makes perfect sense.
