### ISSUE TITLE
Is vfsStream the way to go to test FTP and SFTP ?

### ISSUE THREAD

**Issue by hugsbrugs** [mikey179/vfsStream#146]
Hi there,

I think almost everything is in the title :) I'm creating a package to manage FTP and SFTP transfers, I've built my own tests with real servers but I can't figure out how to test with PHPUnit and vfsStream ...

If you have ideas to share, let me know ! Thanks

**Comment by mikey179** [comment]
Unless your package uses the filesystem functions of PHP I don't think vfsStream can help you with that.

**Comment by dogmatic69** [comment]
It does work for FTP using native file methods. You just nee to use URL's like the following on FTP

    ssh2.sftp://username:password@host/path/to/file.ext

And setup a FS like this:

        vfsStream::setup('username:password@host', null, [
            'music' => [
                'abc.mp3' => 'data',
            ],
        ]);

    vfsStream::url('music/abc.mp3'); // vfs://username:password@host/music/abc.mp3

**Comment by mikey179** [comment]
Thanks @dogmatic69 for sharing this.

Will close this now, as it's not an issue per se.
