### ISSUE TITLE
vfsStream+curl bug on Windows PHP (XAMPP)

### ISSUE THREAD

**Issue by Arzerilla** [mikey179/vfsStream#151]
I'm using PHP Unit in Windows 
If you try to mock the file system with vfsStream and open the mocked file with curl you get an error
cannot represent a stream of type user-space as a STDIO FILE*
In Linux everything is ok.

Tested with PHP 5.6.30

<?php
// composer require mikey179/vfsStream
require 'vendor/autoload.php';
\org\bovigo\vfs\vfsStream::setup();

$fh = fopen('vfs://root/result1.txt', 'w');
$ch = curl_init();

// Windows: ERROR curl_setopt(): cannot represent a stream of type user-space as a STDIO FILE*
// Linux(CentOS6) it's ok
curl_setopt($ch, CURLOPT_FILE, $fh);
curl_exec($ch);

readfile('vfs://root/result1.txt');

**Comment by mikey179** [comment]
Can you add some example code to reproduce the behaviour? I can't imagine why you would want to open the mocked file with curl. Just looked into the ext/curl doc, is that related to [curl_file_create()](http://php.net/manual/en/curlfile.construct.php)?

**Comment by Arzerilla** [comment]
Sure, I'm using your library for unit test of a API suite, so i have to curl_setopt the file
Here's a code snippet

`<?php
// composer require mikey179/vfsStream
require 'vendor/autoload.php';

\org\bovigo\vfs\vfsStream::setup();

$fh = fopen('vfs://root/result1.txt', 'w');
$ch = curl_init();

// Windows: curl_setopt(): cannot represent a stream of type user-space as a STDIO FILE*
// Linux: it's ok
curl_setopt($ch, CURLOPT_FILE, $fh);
curl_exec($ch);

readfile('vfs://root/result1.txt');`

**Comment by mikey179** [comment]
As I currently have no Windows machine available I dived into the sources a bit. It seems like on Windows it tries to cast the vfs stream to a regular file which is not supported by vfsStream as it would defeat the purpose of having the file in memory. Probably next week I'll have access to a Windows machine so I can test if this theory holds.

**Comment by Arzerilla** [comment]
thanks a lot, if you need more info i'm happy to help

**Comment by Arzerilla** [comment]
anything new?

**Comment by mikey179** [comment]
Sorry, unfortunately not. Got access to a Windows machine, but didn't get around to dive into this yet.

**Comment by mikey179** [comment]
Finally got around to look into it. It is indeed the case that on Windows it tries to cast the vfs:// stream into a regular file. As this is not supported (the implementation in vfsStream simply returns `false`) it fails with the warning you see.

I don't see how this can be worked around without actually creating a (temporary) real file by vfsStream. However, this would defeat a promise of it: not having to clean up any file leftovers from a test, regardless of whether it succeeded or failed.

**Comment by mikey179** [comment]
After thinking about this some more I decided to not fix this behaviour for Windows because the promise of vfsStream is to never leave any leftovers, and the only fix possible would violate this promise.
