### ISSUE TITLE
Problem with rar archive mock

### ISSUE THREAD

**Issue by 6ecuk** [mikey179/vfsStream#154]
Hi. "ext/zip seems not to support userland stream wrappers, so it can not be used in conjunction with vfsStream" - this issues extend on rar extension ?

**Comment by mikey179** [comment]
I never tried the rar extension. Do you receive any error messages when trying it?

**Comment by 6ecuk** [comment]
Yeap. Have error with message "file open error"

**Comment by mikey179** [comment]
I tried to look into the extension's source to see if I can spot anything, but I have a hard time to understand it in detail. So my guess is like the zip extension it doesn't support userland stream wrappers.
