### ISSUE TITLE
Risky tests

### ISSUE THREAD

**Issue by eigan** [mikey179/vfsStream#160]
PHPUnit is reporting that there are 208 risky tests at the moment. This is because these tests are not using the PHPUnit methods for assertions. 

Would you be interested in a pull request for converting from your `bovigo\assert` to PHPUnit methods?

EDIT: This is not reported on Travis for some reason. hm

**Comment by mikey179** [comment]
As I converted them recently from PHPUnit to bovigo/assert I don't want to convert them back. ;)

However, over at https://github.com/mikey179/bovigo-assert I'd be interested in why you are getting 208 risky tests when I and Travis CI don't...
