### ISSUE TITLE
A way to test a method that uses `filemtime()` providing a custom time.

### ISSUE THREAD

**Issue by e200** [mikey179/vfsStream#161]
I'm testing this peace of code:

```php
/**
* Returns the last source modification time.
*
* @return int
*/
public function lastSourceModTime()
{
    return filemtime($this->source);
}
```
and i really need to provide a custom modification time to test functions behaviors.
Is there a way to provide a custom modification time instead of the current `time()` setted by vfsStream on create a virtual file???

**Comment by mikey179** [comment]
Sure, you can do that when creating the file, e.g. with `vfsStream::newFile(‘foo.txt’)->lastModified(100)`. Works the same way with directories. See [vfsStreamWrapperFileTimesTestCase](https://github.com/mikey179/vfsStream/blob/master/src/test/php/org/bovigo/vfs/vfsStreamWrapperFileTimesTestCase.php) for other examples.
