### ISSUE TITLE
Seeking past EOF

### ISSUE THREAD

**Issue by downsider** [mikey179/vfsStream#169]
Currently, it is possible return an offset value with `ftell()` that is past the end of a VFS stream. 

I am working on a system that processes lines of unknown length from a large file containing an arbitrary number of lines. As the file can be very large, I wanted to segment the file up into batches that could be processed in parallel.
To make sure each batch doesn't contain partial lines, I'm setting a batch size in bytes then using `fseek()` to move ahead by that number and `fgets()` to read to the end of the line to find the end byte offset. Each process will then process individual lines, beginning from a starting byte offset and stopping when it reaches the end byte offset.

A simplified example of the method is below:
```
$batchSize = 100000;
$batches = [];
while (!feof($file)) {
    $start = ftell($file);
    fseek($file, $batchSize, SEEK_CUR);
    fgets($file);
    $end = ftell($file);
    $batches[] = ["start" => $start, "end" => $end];
}
```

When testing this code using vfsStream, I noticed that for the last batch, the `$end` position was greater than the length of the file; it was always `$start + $batchSize`. Working backwards, I found that VFS was seeking past EOF (which is fine) but was setting the internal offset to the requested seek position. This is unexpected behaviour as you wouldn't think the internal pointer would advance past EOF

**Comment by mikey179** [comment]
I'm not sure that this is a specific problem of vfsStream. If I use your example and apply it to a smaller real file with a smaller batchsize the last `$end` position is also larger than the length of the file:
```php
$batchSize = 100;
$batches = [];
$file = fopen(__FILE__, 'rb');
echo 'Filesize: ', filesize(__FILE__), PHP_EOL;
while (!feof($file)) {
  $start = ftell($file);
  fseek($file, $batchSize, SEEK_CUR);
  fgets($file);
  $end = ftell($file);
  $batches[] = ["start" => $start, "end" => $end];
}

echo 'Last pos: ', ftell($file), PHP_EOL;
var_dump($batches);
```

```bash
$ php foo.php
Filesize: 359
Last pos: 439
array(4) {
  [0]=>
  array(2) {
    ["start"]=>
    int(0)
    ["end"]=>
    int(118)
  }
  [1]=>
  array(2) {
    ["start"]=>
    int(118)
    ["end"]=>
    int(220)
  }
  [2]=>
  array(2) {
    ["start"]=>
    int(220)
    ["end"]=>
    int(339)
  }
  [3]=>
  array(2) {
    ["start"]=>
    int(339)
    ["end"]=>
    int(439)
  }
}
```

**Comment by downsider** [comment]
Sorry, only just realised this hadn't been closed.

You're right, it seems this is how the underlying C functions work (for [reasons](https://stackoverflow.com/questions/17263830/fseek-on-a-position-beyond-eof-does-not-trigger-eof-using-feof-how-come#17263857)), so both PHP and VFSStream are correct in their implementation.

For anyone else finding this issue; the trick is to check for EOF directly after a read (`fgets`, etc...), at which point `$end` is `$start` plus the length of the string returned by `fgets`
