### ISSUE TITLE
Odd behaviour on CentOS (and RHEL)

### ISSUE THREAD

**Issue by dinkel** [mikey179/vfsStream#81]
I just had to find out, that CentOS (and obviously RHEL) have PHP installed without the 'posix' module. This leads to an odd behaviour in 'is_writable'. See the console capture that shows the problem:

    $ cat composer.json 
    {
        "require": {
            "mikey179/vfsStream": "*"
        }
    }
    $ php composer.phar install
    Loading composer repositories with package information
    Installing dependencies (including require-dev)
      - Installing mikey179/vfsstream (v1.2.0)
        Downloading: 100%         

    Writing lock file
    Generating autoload files
    $ cat posix_module_test.php 
    <?php

    require_once "vendor/autoload.php";

    use org\bovigo\vfs\vfsStream;

    vfsStream::setup("base", 0755);

    $stat = stat(vfsStream::url("base"));

    $expected_uid = trim(`id -u`);

    $actual_uid = trim($stat["uid"]);

    if ($expected_uid != $actual_uid)
    {
        echo "Failed asserting that " . $actual_uid . " is " . $expected_uid . "\n";
    }

    if (!is_writable(vfsStream::url("base")))
    {
        echo "This wrongly means that the directory is said to not be writable!\n";
    }
    $ php -m | grep posix
    $ php posix_module_test.php 
    Failed asserting that 0 is 500
    This wrongly means that the directory is said to not be writable!
    $ sudo yum install php-process
    $ php -m | grep posix
    posix
    $ php posix_module_test.php 
    $ 

The problem - as far as I understand it - lies in the fact, that the virtual 'base' driectory is created as root (0) because it get's the UID through vfsStream#getCurrentUser(). The PHP function 'is_writable' is using the correct current user, which is 500 in my case and therefore is *not* allowed to write to the virtual 'base'.

I cannot really say what my expectations are: Is it simply a 'Known issue' or is there a possibility in the code to overcome this odd behaviour?

**Comment by mikey179** [comment]
I decided to not look into any further possibilities. Instead, I added a note in the [requirements](https://github.com/mikey179/vfsStream/wiki/Requirements) that Posix must be enabled. As on Windows no Posix is available I can't add it to the requirements in the `composer.json` file.
