### ISSUE TITLE
vfsStream is not working with Symfony/Finder version superior to 2.5.3

### ISSUE THREAD

**Issue by nchagrass** [mikey179/vfsStream#95]
Hello,

I wanted to know if anyone is experiencing the same issue,
symfony/finder does not return the content of a vfs directory any more with a version superior to 2.5.3

Any idea ?

**Comment by nchagrass** [comment]
I can't find any explanations.

**Comment by floverdevel** [comment]
same problem here with :
symfony-components-finder (v2.6.3)
vfsStream (v1.1.0)

could not test with other installation ...

**Comment by mikey179** [comment]
Just tested with the latest Finder version 2.6.5:
```php
$root = vfsStream::setup(
        'root',
        null,
        array(
                'foo' => array(),
                'bar' => array('yo.txt' => 'Hello world'),
                'baz.txt' => 'Nice to meet you.'
        )
);

foreach (Finder::create()->in($root->url()) as $file) {
     var_dump($file);
}
```

This works quite well. So it seems very much to depend on the features of Finder which are used.
